
# General information {.unnumbered}

## Aims and learning outcomes

This course will help you develop a solid foundation in answering biological questions with quantitative data. Moreover, the approaches you will learn are generally applicable to using data to solve problems, an increasing important skill in a world more and more dominated by data.

[The Learning Objectives of the course](https://opetchey.github.io/BIO144_Course_Information/3.1-learning-objectives.html) tell you what you need to learn and know. Hence, it is very important for you to be very clear about the learning objectives of the course. They will help you know what you're expected to learn and what you will be examined on. If you can achieve all of the learning objectives, you will be very well prepared for a great future in data analysis (and for the exam).

## Course schedule

The course runs during the 14-week spring semester. The course has 12 weeks of new content, and 2 weeks of self-study (no new content). Each of the 12 weeks of new content has a set of learning objectives. Each week has four parts: a lecture, homework, a practical session, and a practice quiz.
 
Lectures are on Monday mornings, 8:00 - 9:45. Practical sessions are on Thursday or Friday afternoons, 13:00 - 14:45.

You'll be assigned to a practical session on either Thursday or Friday. If at any point you wish to change afternoons permanently, contact `studienkoordination@biol.uzh.ch`. If you want to swap days for just one or two weeks, please do so without asking.

Please see the "Year specific information" section below for a detailed course schedule.

**Please note that the day of the last practical session in the last week of the course (usually last Friday of May) is the last day that we can guarantee that you will be able to get help with any problems you have with the course content. After that, we will not be available to help you with content-related questions. We of course remain available to answer questions about the examination arrangements.**

## What should I already know?

Please see the section in OLAT "Previous Knowledge".


## Expected workload

The course is worth 4 credit points, so with 1 CP being approximately 30 hours work, requires around 120 hours study. Approximately one third of this is "in class" and two thirds is self-study, including in-course assessments and preparation for the examination.

## Bring your own laptop

Please bring your laptop to class. There are some power outlets in the lecture theatre, but best will be to make sure that your laptop has sufficient battery charge to last the duration of the class (up to 2 hours), and consider using an external additional battery (powerbar?) if required. Please make sure you know how to use your laptop (some people are sometimes not so sure, perhaps because its new.) Your laptop must be able to connect to the wireless internet at UZH.

## Software

We will be using three computer programmes during class (as well as the usual suspects, such as an internet browser etc.). Please make sure you have them:

1. A spreadsheet programme, such as Microsoft Excel, Apple Numbers, or OpenOffice.


2. [The R software environment for statistical computing and graphics](https://www.r-project.org).


3. [Rstudio](https://posit.co/downloads/). We use RStudio to interact with R. Rstudio has lots of features that make working with R much much easier and enjoyable.

If you need any help setting up your laptop with R and RStudio, please look at relevant section of the "Getting R & RStudio" section of the "Previous Knowledge" section of the course. If you still have problems, no worries... ask for help during the first practical.

## RStudio server

In the final exam you will have to use RStudio server. You are welcome to use it during the course also. You can access it at the following URL: <https://rstudio.mnf.uzh.ch/>. You can log in with your UZH username and password.

## What to do each week

* Attend the lecture.

* After the lecture and before the practical do the homework.

* Come to and do the practical.

* Do the practice quiz.

* Have fun ;)



## Course texts

The required content of the course is all available in the course book: [BIO144 Course Book](https://opetchey.github.io/BIO144_Course_Book/). The lectures will help you understand the content of the book. The homework and practicals will also help you learn the material. Practice quizzes will help you check your learning, and prepare for the final exam. All of this will also help you develop your skills in R, which will also be required in the final exam. 

There is other optional reading that we may suggest to you during the course. This is listed below. Textbooks for optional reading are in the main library, and should be accessible electronically through the main library.

Optional reading comes from the following books. Also each chapter of the course book suggest reading to further your understanding.

* [*Linear Regression, Seminar für Statistik, ETH Zürich*(2008 / 2013) Werner Stahel.](https://github.com/opetchey/BIO144/raw/master/9_assets/Stahel_LinReg.pdf) And here is an [English version of that text](https://github.com/opetchey/BIO144/raw/master/9_assets/Stahel_LinReg_EN.pdf).
* [*Getting Started with R, An introduction for biologists* (2017, Second Edition) Beckerman, Childs & Petchey.](https://academic.oup.com/book/27290) (**DO NOT USE THE FIRST EDITION!**). The link is to the book on the Oxford University Press website; full access to the book will require you have a UZH ip address (i.e. are on the UZH network or VPN into it).
* [Insights from Data](https://academic.oup.com/book/39565) with R, by Petchey, et al. (Same access information as the previous book in this list).
* *The New Statistics with R, An Introduction for Biologists* (2015, First Edition) Hector. [Ebook via UZH library.](https://academic.oup.com/book/32474)




Some other nice (though optional) texts that you might find interesting.

* *Regression; Models, Methods and Applications* (2013 Edition) Fahrmeir, Kneib, Lang & Marx.


* *The Analysis of Biological Data* (2015, Second Edition) Whitlock & Schluter.


* The Essential Guide to Effect Sizes. Statistical Power, Meta-Analysis, and the Interpretation of Research Results (2010, First Edition) Ellis. [Ebook via UZH library.](http://ezproxy.uzh.ch/login?url=http://dx.doi.org/10.1017/CBO9780511761676)


* *Statistics: An Introduction using R* (2011, Second Edition) Crawley.






## Getting datasets

Various datasets are used in the course.

**Datasets used in the homework and practical** are available as a zip file here: [zip file of all the datasets here](https://github.com/opetchey/BIO144/raw/master/3_datasets/all_datasets_bio144.zip), which you will then need to unpack before use.

**Datasets used in the course book** are available in a different zip file, which is provided in the course book (Preface).

**Datasets associated with the book Getting Started with R**, by Beckerman, Childs, and Petchey [here](http://r4all.org/books/datasets/).


IMPORTANT: if you open the downloaded file in Excel, perhaps to have a look at it, then ***DO NOT, UNDER ANY CIRCUMSTANCES, ASK OR ALLOW EXCEL TO SAVE IT***. (Excel does not like R and will do everything in its power to mess things up for R. Don't let it do that.)






## Attendance

**Attending class is a really good idea!**:

"*attendance [is] a better predictor of college grades than any other known predictor of academic performance*",

Credé, Roch, & Kieszczynka, 2010. [The full article.](https://journals.sagepub.com/doi/abs/10.3102/0034654310362998)

We give you the freedom to use the learning materials and opportunities in the way that suits you best. We strongly believe that attending the practical classes and lectures will be an efficient, fun, and valuable way for you to learn.

We will not be tracking attendance. If you do not come to class (practical or lecture) the only penalty you will potentially experience is loss of some learning opportunity.

**What if I was ill or otherwise unable to attend?** Please use your initiative to catchup. Lectures will be available as podcasts. Ask for help from friends for help with practicals. And whatever else you can think of.


## Self study weeks

### Consolidate, review, reinforce, expand!

During approximately two weeks there is no new content. During these week you should take the opportunity to consolidate, review, reinforce, expand!

Here is some optional reading you could look at during those weeks: 

* [Retire Statistical Significance](Amrhein_etal2019.pdf)
* [Interleaf from Whitlock and Schluter: Statistical significanc vs. biological importance](significanceVSimportance_Whitlock.pdf)
* [Interleaf from Whitlock and Schluter: Correlation vs. causation](correlationVScausation.pdf)
* [P-Werte in der NZZ (3. April 2016)](NZZ_April2016.pdf) (You will have to zoom in and probably read it on the screen!)
* And finally, a really thoughtful article in one of the world's leading scientific journals:
[S. Goodman (2016): Aligning statistical and scientific reasoning](Goodman_2016_Science.pdf)

## Assessment

There will be two assessment-related types of activity:

### 1. Weekly practice quizzes

These are only for you. Your scores do not contribute to anything. The are intended:

* To make sure you know if you’re learning and understanding the material.
* To motivate you to keep up with the content of the class, and thereby reduce the chance of you falling behind and then having trouble in the final exam.
* To give you practice with the types of questions that will be in the final examination.

There is no deadline for the practice quizzes. You can do them whenever you like. You can do them multiple times if you like.

### 2. The final exam (and the resit exam)

A final assessment during the module examination period. Your performance in this is the only determinant of your final grade.

**Examination date and time:** Please see the Studium Biology, Modulprufungen im Grundstudium web page and the links therein for the examination dates and other important examination information.

***This information is draft for 2026 and may still be changed.***

Further information:

* The exam will contain about 40 questions. Each will be one of three types: single choice, multiple choice, or numeric. Single choice is a question with several possible answer, of which only one is correct -- you indicate which. Multiple choice is a question with several possible answers; none, 1, 2, 3, or 4 may be correct -- you indicate which. Numeric requires you to enter a number to answer the question.
* A mock exam will be available on OLAT. The mock exam is intended to give you experience with the types of questions that will be in the final examination. It will be similar in terms of the types of questions and structure, and is intended to be similar in difficulty.
* During the exam you are allowed **three sheets of A4 paper** that you may put information on both sides of.
* You are allowed to bring into the exam one translation dictionary (Übersetzungswörterbuch) (e.g., an Englisch–Deutsch-Wörterbuch / English–German dictionary). Examination staff should be allowed to inspect this resource. 
* You will need to present your UZH card during the exam, to verify your identity.
* You will take the exam on your laptop.
* You will need to use your laptop continuously during the two hours of the exam. Some power outlets are available, but best is to make sure you have enough battery power to last the exam.
* Your laptop must connect to the internet via wifi.
* You will take the exam in a special instance of OLAT from within the *Safe Exam Browser* that must be installed on your computer.
* From within the Safe Exam Browser you will be able to use RStudio Server.
* There will be a mandatory practice exam experience including use of the Safe Exam Browser. Details will be sent to you.
* The exam is in English.
* You must agree with an Honour Code on OLAT immediately before you take the exam. 
* You will sit the exam in a lecture theater on the Irchel Campus.
* The final exam requires you to analyse some datasets that are provided to you. Some students have reported that they didn't have enough time during the exam, so please ensure that you can do things like importing data quickly and easily.
* Your working (e.g. any R code your write) is not assessed directly. It is assessed indirectly by whether you answer a question correctly.
* During the exam, if you have any trouble importing the data, please immediately ask for help. 
* When answering numeric questions, the default is to give your answer with precision of 2 decimal places. Some questions specify to give the answer to a different number of decimal places. Please be careful to take care of this.


## Important information about the "mandatory practice exam experience"

This experience is mandatory so that we and you can know that the exam system works on your computer, and if not we can fix any issues before the examination. It also gives you experience of the system. Do not use the number and type of different types of question as an indicator of anything about the final exam.

[Here are the questions and solutions that are used in the practice exam experience](https://github.com/opetchey/BIO144/raw/master/2_content/xtras/BIO144_exam_preparation_solutions.pdf).

You will be informed by email when the practice exam experience is, and all further details.


## Getting help

We aim that you can ask for help about anything and get a useful answer as soon as possible. The following guidelines will help you get fast and useful help. The primary ways to ask for help are:

1. During the practicals on Thursday and Friday.
2. Anytime on the Discussion Forum of this OLAT course. We aim that you get a response in less than two days. Anonymous posts are possible.
3. During and after lectures.

Of course, please feel free to email Owen directly if you wish (but he may ask you to post on the Forum if he feels that would be better). Please don't hesitate to ask for help!


### Posting code problems on the Discussion Forum

The Wiki:FAQ contains a page ***How to ask a question so we can easily help***. Please take a look.

### Specialist statistical assistance

I (Owen) am not a statistician. Hence, I might be unable to answer some of your questions about more statistical issues, particularly as we experience more and more complex statistics. To deal with this, Prof. Furrer has agreed to help with about statistics that I cannot answer (or cannot answer fully). Please post them as a new thread in the discussion forum.  Include as much information as possible, including R code and output as appropriate. Please do not contact Prof. Furrer directly. We will then contact Prof. Furrer and feedback the answer to you.


## Giving feedback

Your views on the course are really important to us. What works well, what doesn’t work so well, what content is particularly important, what content is not so important, what content is missing?

There are several ways of providing feedback.

1. During the course, you can tell us in person during class, and can make posts on the Forum. Such feedback during the course has the potential to improve the course for you. I.e., we might be able to change something quickly, so your and your fellow students’ experience of the class is improved.
2. Fill in the "official" course evaluation form. Details to follow.
3. If have anonymous feedback to give us before or after the official course evaluation then please write on some paper and post it through the University internal mail to us.


## Course language

The course will be mostly in English. Many of the TAs speak and understand English and German. Prof. Petchey best understands and speaks English.

Please let us know how we can assist with any challenges this presents.

[Here is a web page that gives most common (and many not so common) statistical terms in a multitude of languages!](http://isi.cbs.nl/glossary/index.htm)


## Reference letters

The course instructors and the TAs try to get to know each of you during the course, particularly in the practical classes. That said, it is unlikely we gain enough experience of you to write for you a meaningful letter of reference / recommendation. Better will be to develop relationships during subsequent block courses that can lead to meaningful letters.



## Example solution scripts

Some example solution scripts can be found here at the link below. However, in 2026 these are not necessarily up to date, so please beware. Also, please control your use of these example scripts carefully. Students in previous years have said they felt that they sometimes looked at the solutions to early or too quickly. They are provided because many students over many years have asked for them.

<https://github.com/opetchey/BIO144/tree/master/6_example_scripts>


## Lecture podcasts

All lectures will be recorded and made available for later viewing.

## Probeprüfung (Practice exam experience)

In mid to late May there will be a mandatory practice exam experience. This is to make sure that you can use the system that will be used for the final exam, and to give you experience with it.

The most important aims of the Probeprüfung are:

1. Check you can use the Safe Exam Browser on your computer, and if not to fix any issues before the examination.
2. Check that you can log in to the exam environment.
3. Check that you can log in to RStudio server from within the exam environment.

Please note that you can do 1. and 2. independent of the Probeprüfung, and you are encouraged to do so. You can make a [SEB-Testlauf with details here](https://www.zi.uzh.ch/de/support/e-learning-and-examination/students/online-exams/seb-test-runs.html). You can make a [SEB Funktionstest with details here -- search for BIO144](https://www.zi.uzh.ch/de/support/e-learning-and-examination/students/online-exams/exam-overview.html).

[ZI information about online exams -- very useful for you to read and understand.](https://www.zi.uzh.ch/en/support/e-learning-and-examination/students/online-exams)

### Passkeys for authentication

Passkeys for authentication do not work with SEB in general. This means that if you have a passkey for UZH-Login (Rstudio) or edu-ID-Login (OLAT), login for these may fail. Therefore, passkeys have to be removed for UZH-Login (Rstudio) & edu-ID-Login (OLAT). Please see the section below for instructions on how to do this (you must remove them from both accounts, UZH-Login and edu-ID-Login, and in both cases you must remove them in your authenticator app and on the Microsoft website).

### Check that you can use the Safe Exam Browser

The Probeprüfung involves you starting the Safe Exam Browser (SEB) by clicking on a link in a website. If this works correctly the SEB will start up and you will be presented with log in prompt.

Things that can go wrong, and possible solutions:

* You may have clicked the wrong link. Try again, and make sure you click the correct link.
* You may be told your SEB version is wrong. If so, update your SEB to the required version and try again. More info can be found here [SEB installation](https://www.zi.uzh.ch/de/support/e-learning-and-examination/students/online-exams/seb/installation.html)
* You may have some other issue... contact ZI Support for help.

### Check that you can log in to the exam environment

After the SEB starts, it should open and prompt you to login with your Switch Edu-ID credentials. Do this.

Things that can go wrong, and possible solutions:

* You may have entered the wrong username or password. Try again, and make sure you enter the correct username and password.
* After you enter your username and password, a window opens and the process of authenticating starts but then stalls. This is probably caused by you having a passkey configured. See below for detailed instructions on how to fix this issue.
* You may have some other issue... contact ZI Support for help.


### Check that you can log in to RStudio server from within the exam environment

Once logged in you will see the exam environment where you must first confirm that you have read the Ehrenkodex. Only after you confirm the Ehrenkodex can you start the exam. Once you start the exam, you will see 40 questions. In each question there is a link to RStudio. It is very important that you check that you can log in to RStudio server from within the exam environment, and if not to fix any issues before the examination.

Things that can go wrong, and possible solutions:

* The exam won't start. Check that you have confirmed the Ehrenkodex. If not, do so and try again.
* The username and or password you use to log in to RStudio server is not recognised. The username and password are *NOT* the same as your Switch Edu-ID username and password. Try again, and make sure you enter the correct username and password. These are the username and password you use to log in to your email.
* After you enter your username and password, a window opens and the process of authenticating starts but then stalls. This is probably caused by you having a passkey configured. See below for detailed instructions on how to fix this issue.


**How to fix the issue of authentication stalling when trying to log in to RStudio server from within the exam environment**

Login to OLAT and RStudio in Safe Exam Browser will not work if you have a passkey configured for your UZH Microsoft account.

Before making any changes, always ensure that you have at least one backup authentication method available. Otherwise you may lock yourself out of your account.

You can check your authentication methods here (outside SEB, in a normal browser):
https://mysignins.microsoft.com/security-info

Additional UZH instructions for MFA setup are here:
https://www.zi.uzh.ch/en/support/Outlook-und-Kollaboration-Office-365/setup-multifactor-authentification.html#Set_up_Multifactor_Authentication

Then follow these steps:

1. Open the (Microsoft) Authenticator app.
2. Select the University of Zurich UZH account.
3. Tap the gear icon / Settings.
4. Select Delete passkey.
5. Confirm deletion of the passkey.

Next, also check that no passkeys remain configured in your Microsoft account:

1. Open https://mysignins.microsoft.com/security-info
2. Review the listed authentication methods.
3. Remove any remaining passkeys associated with your UZH account.

Then:

1. Restart the mock exam from the exam overview page.
2. Try logging in to RStudio again.






