
# Previous knowledge {.unnumbered}

Many of you already have skills and knowledge that are important for data analysis in biology, from previous learning -- in particular, if you have taken them, from MAT183 (Stochastik für die Naturwissenschaften) and from BIO134 (Programming in Biology). This chapter covers what you should already know, and why.

You'll greatly benefit from having a reasonable recall of this material, and this chapter is meant to help with that. None of it is mandatory, but it's likely to be very useful. Here are some things you might benefit from doing before the first class:

* Review the material from your previous courses -- i.e. review the stuff you can't quite remember!
* Work through the self-tests of your recall of this material, and the material on getting set up with R and RStudio (see "Checking and practising this material" below).
* If you'd like a refresher on R / RStudio specifically, work through the "Getting R & RStudio", "Getting to know R", "Help about R and RStudio", and "What are add-on packages?" sections of the same resource.

Please note that this chapter is not exhaustive -- there might be other things you've previously learned that are also useful for BIO144.

## What you should already know

### From MAT183 -- Stochastik für die Naturwissenschaften

* Methods for describing characteristics of some data. For example, measures of where the centre of the data is (e.g. mean, median, mode), measures of the spread of the data (e.g. quartiles, variance, standard deviation, standard error), and measures of the symmetry of the spread (e.g. skew). Also kurtosis, i.e. how "peaked" a distribution is, and when we'd say a distribution is bimodal.
* The definition of, and the difference between, a *population* and a *sample*.
* Basic use of R and RStudio, including basic arithmetic on scalars and vectors, use of logical operators (`<`, `>`, `==`, `!`, `&`, `|`), importing data into R, and getting basic summary information about your data (e.g. mean, median, variance, standard deviation).
* Basic probability. For example, what is the probability of getting five heads if we toss a fair coin seven times? What is the probability that, given a couple has three children, at least two are boys?
* The importance and characteristics of a few probability distributions: normal, binomial, Poisson, exponential. Many methods of data analysis require at least a basic understanding of these. You will have worked with these distributions in R, using functions such as `dnorm()`, `pnorm()`, `qnorm()`, and `rnorm()`.
* Frequency distributions (histograms) are important for visualising the distribution of your data. You should know what these are and how to make them in R, e.g. using the `hist()` function.
* As well as histograms, you should know when and how to make box-and-whisker plots, QQ-plots, and bivariate scatterplots.
* The statistical concepts: expectations, parameters, parameter estimates, the central limit theorem, hypothesis testing, and standard error of the mean.
* A few basic statistical tests: the one- and two-sample *t*-tests, and the chi-squared test. You should know when to use them, what they can tell us, and how to implement them in R.

### From BIO134 -- Programming in Biology

In BIO134 you spent a lot of time learning concepts and practices of programming, using the language Python. In BIO144 you'll use a different language, R (via RStudio), which you'll already have used a bit in MAT183. There are lots of similarities between Python and R, so it's worth applying what you learned in BIO134 in this class (though there are also differences, so don't expect your Python code to work unchanged in R!). For example, you'll benefit from recalling what you learned about functions, strings, files, plotting, and data analysis such as Spearman correlation. You'll also have learned that accuracy really matters when coding -- a single wrong character can have very unwelcome consequences.

### Other prior knowledge

This will be useful to review before the course starts, but will also be recapped during it.

* The equation of a straight line.
* Types of variable: numeric, continuous, discrete, categorical, dependent, independent, explanatory, response.

## Notation

An overview of the notation used throughout the course is in the ["Notation and some definitions"](https://opetchey.github.io/BIO144_Course_Book/1.1-intro.html#notation-and-some-definitions) section of Chapter 1 of the course book. Most of it is also conventional statistical notation you'll have seen elsewhere. If you have questions about it, use the Discussion Forum, or ask during the first or second practical (i.e. before lecture 3, when we start using it).

## Checking and practising this material

To check your recall of the material above, and to get set up with and comfortable using R and RStudio, work through the [BIO144 Previous Knowledge self-tests](https://rstudio.mnf.uzh.ch:3939/content/6902b39f-65cc-4952-9a24-17cca0fe3ae2). It has:

* **Self-tests** covering the topics above: basic statistics, distributions, probability distributions, data visualisation, important terms and concepts, and basic statistical tests.
* **Getting R & RStudio**: help installing R and RStudio, if you don't have them already.
* **Getting to know R**: a short walkthrough of the very basics of using R, with a script to follow along with.
* **Help about R and RStudio**: how to get help when you're stuck, and some recommended books.
* **What are add-on packages?**: what add-on packages are, and how and when to install and load them, including the `tidyverse`.

None of the self-tests there are graded -- they're just for you, to help you see what you remember well and what's worth reviewing before the course starts.
