
# Unit 1 {.unnumbered}


## Introduction

Welcome to Week 1 of BIO144! Week 1 is a bit different from other weeks because its focuses on introducing how the course is going to work, collecting some data for us to use, and reviewing some material that it would be good for you to remember from previous courses (or learn here if you don't know it yet!)

In subsequent weeks we will focus more on the data analysis concepts and practice.

However, just like all weeks, there is:

* A chapter of the course book.
* A "lecture" on Monday.
* Some homework to ideally do between Monday and the practical on Thursday or Friday.
* A practical session on Thursday or Friday.
* A weekly quiz to check your understanding.


## Course book

This week we will be covering Chapter 1 of [the course book](https://opetchey.github.io/BIO144_Course_Book/).


## Lecture

In the lecture you'll be asked to record some reaction time data about yourself. Use this google form to record the data: <a href="https://forms.gle/woeVDysV48CbcorB7" target="_blank">
  Link to Reaction Time Data Form
</a>

Go to this web page for a tool to record your reaction times: <a href="https://humanbenchmark.com/tests/reactiontime" target="_blank">
  Link to Reaction Time Tool
</a>

The resulting dataset can be access and or downloaded from this web page: <a href="https://tinyurl.com/ye255bdm" target="_blank">
  Link to Reaction Time Dataset
</a>


## Homework, Practical, and Weekly Quiz

These are on this web page: <a href="https://owenpetchey.shinyapps.io/Unit1" target="_blank">
  Link to Homework, Practical, and Weekly Quiz
</a>

