
# Unit 12 {.unnumbered}


## Introduction

Welcome to Week 12 of BIO144!

## Course book

This week we will be covering [Chapter 12: Review: planning and implementing statistical analyses](https://opetchey.github.io/BIO144_Course_Book/12.1-review.html) of the course book.

## Code walkthrough

The R code of this week's chapter is in a code walkthrough script, with a video walkthrough of it. Both are linked at the top of the course book chapter. Work through them before the practical: the last section of the script ("Practical toolbox") shows code that this week's practical uses but the chapter does not.

## Learning objectives

These learning objectives, together with the content of the course book chapter, define what you need to know for the exam.

```{r}
#| echo: false
#| output: asis
source("learning_objectives/lo.R")
lo_list("12.1", "learning_objectives")
```



## Lecture

Please attend the lecture. If for any reason you can't, please watch the podcast, which is available on OLAT.



## Homework, Practical, and Weekly Quiz

Available [here](https://rstudio.mnf.uzh.ch:3939/content/fa0a83c4-fec9-4557-9f34-d0f36a41cf62). You will need to be on a UZH network to access this link, so if you are not on campus, you will need to connect to the UZH VPN first.


